name: Deploy Express BigQuery API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install express @google-cloud/bigquery body-parser cors

      - name: Configure BigQuery credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GOOGLE_CREDENTIALS }}"
        run: |
          echo "${GOOGLE_APPLICATION_CREDENTIALS}" > /tmp/keyfile.json

      - name: Run the app
        env:
          PORT: 5000
        run: |
          node server.js
